### ISSUE TITLE
Radarr not working

### ISSUE THREAD

**Issue by MagicaNexus** [GreenFrogSB/LDS#1]
When I do localhost:7878, I can't access to the radarr container.
On portainer, it is running.

The error I get is : ERR_CONNECTION_REFUSED

Do you have a solution ?

**Comment by throwaway1010** [comment]
Finally found a solution to this today, 
This post has the solution:
[](https://www.reddit.com/r/radarr/comments/k3xzgw/connection_refused_after_repulling/)

run: 
`wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.0-3_armhf.deb
sudo dpkg -i libseccomp2_2.5.0-3_armhf.deb`

then in the ~/LDS directory run:
`docker-compose up -d` 

This might take a reboot to take effect, I rebooted after installing the package and then I composed the containers and radarr is now working for me as intended.

The owner of this script should probably add this into the script on install.

**Comment by MagicaNexus** [comment]
By my side, i've found a solution with this post here, by replacing `linuxserver/radarr:latest` by `linuxserver/radarr:5.14` on the docker-compose.

Then in the ~/LDS directory run:
`docker-compose up -d`

I know it is not optimised but it is enough for me for now, waiting for an update 👍

Source : https://cutt.ly/uhv6gUq (Reddit)

**Comment by GreenFrogSB** [comment]
Repo updated with the fix of locking Radarr into a specific release version 5.14 for now. 
Thank you guys **@throwaway1010 @MagicaNexus** for finding this out. 

**Fix:**
If you already using LDS from this repo, below is the way of fixing **Radarr not responding on port 7878 even if container is up and running ok** 
If you just cloning it fresh, it will work ok, below is only if you want to fix existing LDS repo on your system. 

Delete radarr container and associated image using Portainer GUI or using below commands
docker stop radarr 
docker rm radarr 
docker image prune -a

Pull prohect changes (**small issue was also fixed that was preventing auto update**) 
cd to ~/LDS
git pull origin main
./deploy.sh

From the menu choose "Build LDS Stack"
Select all the needed containers and OK
For each container choose "Pull full service from template"
docker-compose up -d
