### ISSUE TITLE
Road block after running './deploy.sh'

### ISSUE THREAD

**Issue by ModelSD** [GreenFrogSB/LDS#2]
When entering the LDS directory and running ./deploy.sh, below is the result. 

![image](https://user-images.githubusercontent.com/45953189/103493800-488ec680-4de8-11eb-9f28-c56ae202ed49.png)

**Comment by GreenFrogSB** [comment]
Indeed there was an issue,, I hope it is fixed now. 
If you are stuck on the same place just force update 
git reset --hard
git clean -fd

**Comment by GreenFrogSB** [comment]
Hi ModelSD,
Thank you for bringing this up.
I hope script is now corrected, just force repo update:
git reset --hard
git clean -fd
Please let me know if that worked for you.
Regards
GreenFrog

**Comment by ModelSD** [comment]
Yes!! It worked. Thanks for all your hard work.
