### ISSUE TITLE
stuck when ./deploy.sh

### ISSUE THREAD

**Issue by Rasphenri** [GreenFrogSB/LDS#3]
Hi ;) 

~/LDS $ ./deploy.sh
checking for project update
Depuis https://github.com/GreenFrogSB/LDS
 * branch            main       -> FETCH_HEAD
An update is available for the project

then nothing happen, i need to restart my terminal if i want to enter a new command

even
git reset --hard
and
git clean -fd
don't resolve the problem :/

Can someone help me ? :D

**Comment by GreenFrogSB** [comment]
Hmm it did work for other users and for me.

go in to LDS folder and while you in it execute below:

rm deploy.sh
git fetch --all
git reset --hard origin/main
git pull origin main

Please report back if that helped?

**Comment by GreenFrogSB** [comment]
Fixed with above solution, no new reported.
Case closed
