### ISSUE TITLE
Raspberry Pi version

### ISSUE THREAD

**Issue by Daneng66** [GreenFrogSB/LDS#69]
I am running a raspberry pi 3, is this supported as when all my containers are running it freezes up

**Comment by GreenFrogSB** [comment]
Yes, Pi3 will work ok.
Make sure you use Raspbian Lite 64bit OS.
Do not use Raspbian Desktop, had some issues with Docker on it.
Try to deploy a few containers at the time and see if that works.
Received some update lately that nzbget container is causing problems - if
you need it, try to check if without it all works and then add it to see if
all goes bonkers?
All the Best
GreenFrog

**Comment by Daneng66** [comment]
@GreenFrogSB any ideas why I might not be able to add a root folder in sonarr?

**Comment by Kywalh** [comment]
running on Pi 0 ? 
I only intent to run honeygain on it...

**Comment by GreenFrogSB** [comment]
Depending on the model you have exactly. You need 64bit CPU and 64bit OS on it. There are Pi zero that have only 32bit CPU, honey will not start on it. Check the model you have https://en.m.wikipedia.org/wiki/Raspberry_Pi

**Comment by Kywalh** [comment]
Well, I found a Pi3 and went through the install and configuration.
I started the container but nothing shows up on the dashboard after more than 1h...

How can I know if the container still works properly?

I used my Google credentials but saw later that it shall not. 
Can it be the reason that the "device" doesn't show up in the list?

Thanks

**Comment by GreenFrogSB** [comment]
Possibly, container require you to supply your user and password created on HG website, if you logger with Google oAuth you do not have these details to put in to container.
