### ISSUE TITLE
qBittorrent and Lidarr not starting after powering RPi on

### ISSUE THREAD

**Issue by OBELIKS** [GreenFrogSB/LDS#70]
When system is fully booted all containers start, except for Lidarr and qBittorrent. It's possible to manually start them from Portainer.
What do I need to check?

**Comment by GreenFrogSB** [comment]
Yes, in Portainer you select a container and press Start. 
If you want to permanently make container start after each reboot, edit docker-compose.yml file, find relevant section for the container in question and add "restart: unless-stopped" declaration at the end - look at the other ones as a example. 
Save the file and run "docker-compose up -d" again.
