### ISSUE TITLE
Docker Containers seems to be running but not showing in my dashboard

### ISSUE THREAD

**Issue by titancomputinglegend** [GreenFrogSB/LDS#71]
Running Raspbian Linux 10 (Buster) 32 Bit version
When I tried to deploy LMDS, no issues. Everything went fine. Docker Installation, LMDS stack and the docker-compose as well. 
However, the docker containers seem to be running but it's not showing in my dashboard. I tried reinstalling Raspberry Pi with even the other bit of Raspberry. Still No luck in dashboard.honeygain.com

![image](https://user-images.githubusercontent.com/49803822/232277544-ad21beb7-b83a-4b47-9e4f-0945b19c61ea.png)

**Comment by GreenFrogSB** [comment]
LMDS is running HG container in emulation.
This emulation of x86 CPU on ARM require 64bit ARM CPU and 64bit OS - you say "Running Raspbian Linux 10 (Buster) 32 Bit version" reimage your SD with 64bit Raspbian instead if your Pi can support it of course.
