### ISSUE TITLE
error about the container not made for arm?

### ISSUE THREAD

**Issue by ArielAssaf** [GreenFrogSB/LDS#73]
I get this error:

pi@raspberrypi:~/LMDS $ ./deploy.sh
Checking for project update
Project is up to date
Adding portainer container
...pulled full portainer from template
Adding sonarr container
...pulled full sonarr from template
Adding radarr container
...pulled full radarr from template
Adding jackett container
...pulled full jackett from template
docker-compose successfully created
run docker-compose up -d to start the stack
pi@raspberrypi:~/LMDS $ ^C
pi@raspberrypi:~/LMDS $ docker-compose up -d
Creating network "lmds_default" with the default driver
Pulling sonarr (linuxserver/sonarr:)...
latest: Pulling from linuxserver/sonarr
ERROR: no matching manifest for linux/arm/v8 in the manifest list entries

Any thoughts on what I might have done wrong?

**Comment by GreenFrogSB** [comment]
Basically your ARM procesor is not compatible with the container available. 
https://hub.docker.com/r/linuxserver/sonarr/tags
It means that your Pi CPU might be to old and this container is no longer supporting it.

**Comment by bodison** [comment]
Maybe this will help you. I had to edit the docker compose file to use these:

linuxserver/sonarr:arm32v7-4.0.0-develop
linuxserver/radarr:arm32v7-4.5.2
linuxserver/lidarr:arm32v7-1.1.4
linuxserver/bazarr:arm32v7-1.2.2
ghcr.io/linuxserver/prowlarr:arm32v7-1.5.2
ghcr.io/linuxserver/jellyfin:arm32v7-10.8.10
ghcr.io/linuxserver/ombi:arm32v7-4.39.1
linuxserver/qbittorrent:arm32v7-4.5.3
